AWSTemplateFormatVersion: '2010-09-09'
Description: Create EC2 Alarms For Windows OS - 1.0.1

Parameters:
  InstanceId:
    Description: The EC2 instance ID to associate this alarm with.
    Type: AWS::EC2::Instance::Id
  AlarmSnsTopic:
    Description: SNS Topic for Alarm
    Type: String
  Environment:
    Description: Environment Name
    Type: String
  AfterHourTag:
    Description: after-hours-support tag value
    Type: String
    Default: tagNotAvailable
  ApplicationName:
    Description: Application Name
    Type: String
    Default: appnameNotProvided
  ApplicationRunbookUrl:
    Description: URL to application runbook
    Type: String
    Default: runbookNotAvailable
  CPUThreshold:
    Description: Calculated threshold for CPU Utilization.
    Type: Number
    Default: 90
  MemoryThreshold:
    Description: Calculated threshold for Memory Utilization.
    Type: Number
    Default: 90
  InstanceName:
    Description: Instance Name.
    Type: String

Conditions:
  DeployCustom: !Not 
    - !Equals [ !Ref MemoryThreshold, 0 ] 

Resources:
  WindowsCPUUtilizationAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${Environment}-${InstanceId}-CPUUtilization-Alarm
      ActionsEnabled: true
      AlarmActions:
        - !Ref AlarmSnsTopic
      OKActions:
        - !Ref AlarmSnsTopic
      AlarmDescription: !Sub >-
        {
          "region": "${AWS::Region}",
          "description": "EC2 CPUUtilization Alarm",
          "alarm_name": "CPUUtilization-Alarm",
          "environment": "${Environment}",
          "appname": "${ApplicationName}",
          "URL": "${ApplicationRunbookUrl}",
          "account_id": "${AWS::AccountId}",
          "type": "EC2",
          "instance_name": "${InstanceName}",
          "after-hours-support": "${AfterHourTag}"
        }
      Namespace: AWS/EC2
      MetricName: CPUUtilization
      Statistic: Average
      Period: 300
      EvaluationPeriods: 4
      Threshold: !Ref CPUThreshold
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
      - Name: InstanceId
        Value: !Ref InstanceId
      TreatMissingData: breaching

  WindowsStatusCheckFailedAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub ${Environment}-${InstanceId}-StatusCheckFailed-Alarm
      ActionsEnabled: true
      AlarmActions:
        - !Ref AlarmSnsTopic
      OKActions:
        - !Ref AlarmSnsTopic
      AlarmDescription: !Sub >-
        {
          "region": "${AWS::Region}",
          "description": "EC2 StatusCheckFail",
          "alarm_name": "StatusCheckFailed-Alarm",
          "environment": "${Environment}",
          "appname": "${ApplicationName}",
          "URL": "${ApplicationRunbookUrl}",
          "account_id": "${AWS::AccountId}",
          "type": "EC2",
          "instance_name": "${InstanceName}",
          "after-hours-support": "${AfterHourTag}"
        }
      Namespace: AWS/EC2
      MetricName: StatusCheckFailed
      Statistic: Minimum
      Period: 300
      EvaluationPeriods: 5
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Threshold: 1
      Dimensions:
      - Name: InstanceId
        Value: !Ref InstanceId
      TreatMissingData: breaching

  WindowsMemoryUtilizationAlarm:
    Type: AWS::CloudWatch::Alarm
    Condition: DeployCustom
    Properties:
      AlarmName: !Sub ${Environment}-${InstanceId}-MemoryUtilization-Alarm
      ActionsEnabled: true
      AlarmActions:
        - !Ref AlarmSnsTopic
      OKActions:
        - !Ref AlarmSnsTopic
      AlarmDescription: !Sub >-
        {
          "region": "${AWS::Region}",
          "description": "EC2 Memory Alarm",
          "alarm_name": "Memory-Alarm",
          "environment": "${Environment}",
          "appname": "${ApplicationName}",
          "URL": "${ApplicationRunbookUrl}",
          "account_id": "${AWS::AccountId}",
          "type": "EC2",
          "instance_name": "${InstanceName}",
          "after-hours-support": "${AfterHourTag}"
        }
      Namespace: CWAgent
      MetricName: 'Memory % Committed Bytes In Use'
      Statistic: Average
      Period: 300
      EvaluationPeriods: 4
      ComparisonOperator: GreaterThanThreshold
      Threshold: !Ref MemoryThreshold
      Dimensions:
      - Name: InstanceId
        Value: !Ref InstanceId
      TreatMissingData: breaching
